name: Deploy to GitHub Pages
on:
    pull_request:
        branches:
            - main
        types: [closed]

jobs:
    deploy-gh-pages:
        runs-on: ubuntu-latest
        steps:
            - run: cd app
            - run: yarn run deploy
